#!/usr/bin/env python3
"""Generate reborn-splash-mark.h from Reborn's rendered 480x360 boot frame.

The early splash must hand off to Reborn without a visible change, so the mark
is taken from Reborn's own boot frame (rendered by Y2Reborn's preview tool
from the production quads), not redrawn here. Only the region that differs
from the background is stored, run-length encoded as RGB888. The accent rule
is excluded: the splash draws it itself so it can pulse while waiting.

Usage: make-splash-mark.py BOOT_FRAME.png OUTPUT.h
"""
import sys
from pathlib import Path

from PIL import Image

BG = (0x09, 0x0B, 0x0D)
RULE = (220, 198, 40, 2)  # x, y, w, h — must match Reborn's boot_frame()


def main():
    source, output = Path(sys.argv[1]), Path(sys.argv[2])
    image = Image.open(source).convert('RGB')
    if image.size != (480, 360):
        raise SystemExit('boot frame must be 480x360')
    pixels = image.load()
    x0, y0, w, h = RULE
    for y in range(y0, y0 + h):
        for x in range(x0, x0 + w):
            pixels[x, y] = BG
    if pixels[0, 0] != BG:
        raise SystemExit('boot frame background does not match the splash background')
    box = None
    for y in range(360):
        for x in range(480):
            if pixels[x, y] != BG:
                box = (min(box[0], x), min(box[1], y), max(box[2], x), max(box[3], y)) if box else (x, y, x, y)
    if box is None:
        raise SystemExit('no mark found')
    left, top, right, bottom = box
    width, height = right - left + 1, bottom - top + 1
    runs = []
    previous, count = None, 0
    for y in range(top, bottom + 1):
        for x in range(left, right + 1):
            colour = pixels[x, y]
            if colour == previous and count < 255:
                count += 1
            else:
                if previous is not None:
                    runs.append((count, *previous))
                previous, count = colour, 1
    runs.append((count, *previous))
    data = [value for run in runs for value in run]
    lines = [', '.join(f'0x{v:02x}' for v in data[i:i + 16]) for i in range(0, len(data), 16)]
    output.write_text(
        '/* Generated by tools/graphics/make-splash-mark.py from Reborn\'s boot frame.\n'
        ' * RGB888 runs: count, red, green, blue. Do not edit by hand. */\n'
        '#ifndef REBORN_SPLASH_MARK_H\n#define REBORN_SPLASH_MARK_H\n'
        f'#define RB_MARK_X {left}u\n#define RB_MARK_Y {top}u\n'
        f'#define RB_MARK_WIDTH {width}u\n#define RB_MARK_HEIGHT {height}u\n'
        f'#define RB_RULE_X {x0}u\n#define RB_RULE_Y {y0}u\n'
        f'#define RB_RULE_WIDTH {w}u\n#define RB_RULE_HEIGHT {h}u\n'
        'static const unsigned char rb_mark_rle[] = {\n    ' + ',\n    '.join(lines) + '\n};\n'
        'static const unsigned rb_mark_rle_len = sizeof(rb_mark_rle);\n#endif\n')
    print(f'{output}: {width}x{height} at ({left},{top}), {len(runs)} runs, {len(data)} bytes')


if __name__ == '__main__':
    main()
