# SPDX-License-Identifier: GPL-2.0-only
obj-y += clocks.o pinctrl.o pwrap.o apt32f-wheel.o keypad.o backlight.o
obj-y += mm-clocks.o phy-mt6582.o panel.o
obj-y += usb.o
obj-$(CONFIG_Y2_POWER) += boot.o mt6323-adc.o mt6323-charger.o thermal.o idle.o spm.o
obj-$(CONFIG_Y2_POWER) += mfg-clock.o
obj-$(CONFIG_Y2_POWER) += local-timer.o
obj-$(CONFIG_Y2_POWER) += cpu-dvfs.o
obj-$(CONFIG_Y2_POWER) += workload.o
obj-$(CONFIG_Y2_CONNECTIVITY) += connectivity/
obj-$(CONFIG_Y2_POWER) += cirq.o
obj-$(CONFIG_Y2_POWER) += cpu-options.o
obj-$(CONFIG_Y2_POWER) += pm-journal.o resume-vector.o
obj-$(CONFIG_Y2_POWER) += system-idle.o
