# SPDX-License-Identifier: GPL-2.0-only
obj-y += clocks.o pinctrl.o pwrap.o apt32f-wheel.o keypad.o backlight.o
obj-y += mm-clocks.o phy-mt6582.o panel.o
obj-y += usb.o
obj-$(CONFIG_Y2_POWER) += mt6323-adc.o mt6323-charger.o thermal.o idle.o
