#!/bin/sh
# Normal userspace requests go through the bounded platform coordinator.
case "${0##*/}" in poweroff|reboot) action=${0##*/};; *) exit 2;; esac
[ "$#" = 0 ] || { echo 'Use y2-platform shutdown for normal shutdown; emergency flags are not supported.' >&2; exit 2; }
exec /usr/sbin/y2-platform shutdown "$action" --reason user
