#!/bin/sh
case "$1" in
 start) start-stop-daemon -S -b -m -p /run/y2/power-supervisor.pid -x /usr/libexec/y2/power-supervise ;;
 stop) start-stop-daemon -K -p /run/y2/power-supervisor.pid 2>/dev/null || : ;;
 *) exit 2 ;;
esac
